#!/bin/sh

/usr/bin/invoke_app "$@" -C "python @tool/bin/gsaimage/gsaimage2.py nanohub" -t gsaimage \
                         -e RUN_LOCATION=@tool/bin \
                         -u anaconda3-5.1 \
                         -u pyqtgraph-0.10.0
